name: leaderos-plugin
author: [leaderos, geik]
main: net.leaderos.plugin.Main
version: 1.0
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
    leaderos:
        description: Default command of leaderos
    webshop:
        description: Webshop module default command
    credits:
        description: Credits module command
    bazaar:
        description: bazaar default command
    auth:
        description: Connects your ingame account with website
    donations:
        description: Shows who donated server recently with