name: leaderos-plugin
author: [geik]
main: net.leaderos.plugin.Main
version: 1.0
api-version: 1.13
commands:
    leaderos:
        description: Default command of leaderos
    webshop:
        description: webshop default command
        aliases: ["webstore", "store", "sitemarket", "webmarket"]
    bazaar:
        description: bazaar default command
    auth:
        description: Connects your ingame account with website
        aliases: [web, kayıt, bağlan]