name: LeaderOS
authors: [leaderos, geik]
main: net.leaderos.plugin.Bukkit
version: 1.0
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
    leaderos:
        description: Default command of leaderos
    webstore:
        description: WebStore module default command
    credits:
        description: Credits module command
    creditvoucher:
        description: Voucher module command
    bazaar:
        description: bazaar default command
    auth:
        description: Connects your ingame account with website
    discord-sync:
        description: Sync your account with discord
    donations:
        description: Shows who donated server recently with